#!/bin/sh

if [ "$1" = "" ]
then
    echo Specify a Routine
fi

if [ "$1" = "mine" ]
then
    echo Mining Electroneum
    # Path to the start.sh file
    /Users/jpiglesias/Downloads/minekitten.miner.mac.cpu/start.sh
fi

if [ "$1" = "stats" ]
then
    echo Checking Stats
    open http://minekitten.io/?ref=producthunt#statistics
fi

if [ "$1" = "ops" ]
then
    echo Opening Neotracker
    open https://neotracker.io/wallet
fi
